name: arpahound
description: Network monitor — Wireshark + Speedtest for Android
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  web_socket_channel: ^2.4.0
  fl_chart: ^0.68.0
  shared_preferences: ^2.2.3

flutter:
  uses-material-design: true
