apiVersion: v1
kind: Service
metadata:
  name: arpahound-server-service
spec:
  selector:
    app: arpahound-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080 # Example NodePort; choose a free port in the 30000-32767 range
  type: NodePort
